version: '3'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=password
  web:
    depends_on:
        - db
    stdin_open: true
    tty: true
    container_name: jayson-basic-login
    build: .
    command: /bin/bash -c "rm -f /tmp/server.pid && bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid"
    volumes:
      - .:/app
    ports:
      - "3000:3000"